const URGENCY_CONFIG = {
  High:   { cls: 'urgency-high',   icon: '🔴', label: 'High Priority' },
  Medium: { cls: 'urgency-medium', icon: '🟡', label: 'Medium Priority' },
  Low:    { cls: 'urgency-low',    icon: '🟢', label: 'Low Priority' },
}

function Field({ label, value, wide }) {
  return (
    <div className={`bg-stone-50 rounded-xl p-4 border border-stone-100 ${wide ? 'sm:col-span-2' : ''}`}>
      <p className="text-xs font-semibold uppercase tracking-widest text-stone-400 mb-1">{label}</p>
      <p className="text-sm text-[var(--ink)] font-medium leading-snug">{value || '—'}</p>
    </div>
  )
}

export default function IntakeSummary({ result, onReset }) {
  const urgency = URGENCY_CONFIG[result.urgency] || URGENCY_CONFIG.Medium

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-stone-200 p-8 fade-up">
      {/* Header */}
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="font-display text-2xl text-[var(--ink)]">Clinical Intake Summary</h2>
          <p className="text-xs text-stone-400 mt-0.5">Generated by AI · For staff review only</p>
        </div>
        <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold ${urgency.cls}`}>
          {urgency.icon} {urgency.label}
        </span>
      </div>

      {/* Fields grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-6">
        <Field label="Chief Complaint" value={result.chief_complaint} wide />
        <Field label="Duration" value={result.duration} />
        <Field label="Urgency Level" value={result.urgency} />
        <Field label="Suggested Department" value={result.suggested_department} wide />
      </div>

      {/* AI Summary */}
      <div className="bg-[var(--teal)] bg-opacity-5 border border-[var(--teal)] border-opacity-20 rounded-xl p-5 mb-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-[var(--teal)] mb-2">AI Clinical Summary</p>
        <p className="text-sm text-[var(--ink)] leading-relaxed">{result.summary}</p>
      </div>

      {/* Disclaimer */}
      <div className="text-xs text-stone-400 bg-stone-50 rounded-lg px-4 py-3 mb-5 border border-stone-100">
        ⚠ This summary is for intake documentation purposes only. It does not constitute a medical diagnosis
        or treatment recommendation. All clinical decisions must be made by a licensed healthcare provider.
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button
          onClick={onReset}
          className="flex-1 rounded-xl border border-stone-200 py-3 text-sm font-semibold text-stone-500 hover:border-[var(--ink)] hover:text-[var(--ink)] transition"
        >
          ← New Intake
        </button>
        <button
          onClick={() => window.print()}
          className="flex-1 rounded-xl bg-[var(--ink)] py-3 text-sm font-semibold text-[var(--cream)] hover:bg-[var(--teal)] transition"
        >
          Print / Export
        </button>
      </div>
    </div>
  )
}
